### ISSUE TITLE
500 klaida api/downloads

### ISSUE THREAD

**Issue by Faustasm** [atviriduomenys/katalogas#1024]
Internal Server Error: /partner/api/1/downloads
 Traceback (most recent call last):
   File "X/site-packages/django/core/handlers/exception.py", line 47, in inner
     response = get_response(request)
                ^^^^^^^^^^^^^^^^^^^^^
   File "X/site-packages/django/core/handlers/base.py", line 181, in _get_response
     response = wrapped_callback(request, *callback_args, **callback_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "X/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
     return view_func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "X/site-packages/rest_framework/viewsets.py", line 125, in view
     return self.dispatch(request, *args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "X/site-packages/rest_framework/views.py", line 509, in dispatch
     response = self.handle_exception(exc)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "X/site-packages/rest_framework/views.py", line 469, in handle_exception
     self.raise_uncaught_exception(exc)
   File "X/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
     raise exc
   File "X/site-packages/rest_framework/views.py", line 497, in dispatch
     self.initial(request, *args, **kwargs)
   File "X/site-packages/rest_framework/views.py", line 415, in initial
     self.check_permissions(request)
   File "X/site-packages/rest_framework/views.py", line 332, in check_permissions
     if not permission.has_permission(request, self):
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "X/site-packages/vitrina/api/permissions.py", line 23, in has_permission
     organization, user = get_api_key_organization_and_user(request)

   File "X/site-packages/vitrina/api/services.py", line 53, in get_api_key_organization_and_user
     if isinstance(api_key_obj.representative.content_object, Organization):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 AttributeError: 'NoneType' object has no attribute 'content_object'

**Comment by Grigorjeva11** [comment]
Prašau patikslinti, ar dar aktualu. Jeigu aktualu, pažymėkite prioritetą (P0 - aukščiausias).
