### ISSUE TITLE
Publisher rolė

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#1269]
Iš DCAT-AP:

- **creator** - An entity responsible for producing the dataset.
- **publisher** - An entity (organisation) responsible for making the Dataset available.

`creator` yra institucijos teikiančios duomenis, o `publisher` daugeliu atveju bus VDA, tačiau gali būti ir ta pati institucija, kuri reikia duomenis, jei duomenų atvėrimą daro savarankiškai.

VSSA šiuo atveju būtų `distributor`, t.y. atsakinga už atvirų duomenų platinimą duomenų naudotojams.

Šiuo metu ADP nėra atskira ar organizacija yra creator ar publisher, visais atvejais, daroma prielaida, kad organizacija yra tiek creator, tiek publisher.

Šiuo metu yra įgyvendinta DCAT Attribution funkcionalumas:

- https://github.com/atviriduomenys/katalogas/issues/341
- https://github.com/atviriduomenys/katalogas/issues/43

Reikėtu atskirti `creator` nuo `publisher` ir abi roles padaryti Katalogo dalimi.

Reikia padaryti, kad dabar publikuojami duomenų rinkiniai, būtų administruojami publisher organizacijos, kuri gali nurodyti, kas yra duomenų rinkinio creator.

Tai reiškia, kad duomenų rinkinio formoje, turėtu būti galimybė nurodyti, kas yra `creator` ir kas yra `publisher`.

Reikėtu atskirti, kas gali redaguoti ir kurti duomenų rinkinius:

- Jei organizacija teikia duomenų atvėrimo paslaugas, t.y. jei organizacija yra `publisher`, tada ji gali nurodyti kitą `creator` organizaciją, nurodant duomenų savininką.
- Jei organizacija neteikia duomenų atvėrimo paslaugų, tada `creator` negali būti keičiamas, tačiau galima keisti `publisher`.

Duomenų rinkinio duomenis gali tvarkyti tiek `creator`, tiek `publisher`.

Duomenų rinkinio peržiūros puslapyje, šone rodoma visada `creator`, taip pat ir filtruose, kur filtruojama pagal organizaciją, visada filtruojama pagal `creator`.

Dėl `publisher`, šiuo metu yra šiokios tokios užuomazgos, tik tai vadinama `provider`:

https://github.com/atviriduomenys/katalogas/blob/1660d4d4516e4a45381edcf359ae78f341588f52/vitrina/orgs/models.py#L91

Matyt reikėtu pakeisti į `publisher`.

Apibendrinant:

- ADP gali turėti organizacijas, kurios yra pažymėtos, kaip `publisher`, t.y. tam tikras VSSA prižiūrimas organizacijų sąrašas, kurios teikia duomenų atvėrimo paslaugas.
- `publisher` organizacijos, gali kurti rinkinius ir nurodyti kitą `creator` organizaciją, t.y. gali kurti duomenų rinkinius, jei teikia tai organizacijai duomenų atvėrimo paslaugas, net jei `creator` organizacija neturi koordinatoriaus arba net iš vis nėra užsiregistravusi ADP.
- `publisher` organizacijos yra tos, kurios turi `Organization.provider = True`.
- `creator` visur rodomas, kaip duomenų savininkas (filtruose, statistikoje, duomenų rinkinio peržiūroje ir pan.).
- `publisher` rodomas prie susijusių organizacijų, nurodant ir matyt, galima turėtu atskirą filtrą, pagal publisherius.
- Jei organizacija nėra `publisher` organizacija, tada negali keisti `creator`.
- `creator` gali keisti duomenų rinkinio `publisher`, pasirenkant iš sąrašo organizacijas, kurios yra `Organization.provider = True`.
- Tiek `creator`, tiek `publisher` gali redaguoti duomenų rinkinius, tačiau visi veiksmai turi atsispindėti istorijoje ir turi būti atsižvelgiama į prieigos valdymo teises (https://github.com/atviriduomenys/katalogas/issues/171).

### Susiję

- https://github.com/atviriduomenys/katalogas/issues/1291
- https://github.com/atviriduomenys/katalogas/issues/1290

**Comment by sirex** [comment]
Organizacijos formoje „Atvėrimo duomenų teikėjas“ turi būti rodomas tik super administratoriui.

„Atvėrimo duomenų teikėjas“ reikia pakeisti į „Duomenų atvėrimo paslaugų teikėjas“ (Publisher rolė).

**Comment by Grigorjeva11** [comment]
@sirex Kiek supratau iš pokalbio su Julium, VDA nori, kad būnant publisher, jie galėtu nurodyti organizaciją (creator) taip pat ir iš sąrašo organizacijų, kurios dar nėra registruotos duomenų teikėjais ADP. Kaip elgiamės šiuo atveju?

**Comment by Grigorjeva11** [comment]
Su šia užduotim realizuoti, kad organizacija galėtu būti arba publisher, arba creator.
Visos dabar registruotos organizacijos turi būti priskirtos kaip "creator".
Visoms naujoms organizacijoms skyriama by default rolė "creator".
Organizacijai suteikti rolė "publisher" gali vyr. koordinatorius per administravimo aplinka. (Šia dalį realizuosime su kita užd.)

**Comment by sirex** [comment]
> @sirex Kiek supratau iš pokalbio su Julium, VDA nori, kad būnant publisher, jie galėtu nurodyti organizaciją (creator) taip pat ir iš sąrašo organizacijų, kurios dar nėra registruotos duomenų teikėjais ADP. Kaip elgiamės šiuo atveju?

Dėl šios vietos, reikia, kad @JuliusLADP pakomentuotų.

Asmeniškai, manau, kad jei nėra creator ogranizacijos, tai publisher turėtu galėti ją užregistruoti. Naujos organizacijos registravimas turėtu būti automatizuotas importuojant duomenis iš JAR:

- https://github.com/atviriduomenys/katalogas/issues/331

> Organizacijai suteikti rolė "creator" gali vyr. koordinatorius per administravimo aplinka. (Šia dalį realizuosime su kita užd.)

Gal čia turima mintyje, kad administratorius gali suteikti "publisher" rolę, nes by default visos organizacjos yra "creator"?

Toks funkcionalumas ("publisher" statuso suteikimas) jau dalinai yra realizuotas, organizaciją galima pažymėti kaip "publisher", organizacijos formoje pažymėjus „Atvėrimo duomenų teikėjas“.

**Comment by Grigorjeva11** [comment]
@sirex Taip, turėjo būti "publisher", ne "creator". Pataisiau. Taip pat mačiau, kad dalinai toks funkcionalumas jau yra, tačiau dabar "publisher" rolė gali sau suteikti pati organizacija redaguodama savo duomenis, kas nėra iki galo teisinga šiam atvejui. Priėjome išvados, kad vyr. koordinatorius reguliuos sąrašą organizacijų, kurių duomenis galės valdyti konkretus "publisher". Sąrašą galima bus valdyti administravimo aplinkoje, o pridėdant į sąrašą ADP neregistruotą organizaciją, ji bus automatiškai užregistruota ir priskirtas "publisher" atstovas (jie rinksis, kuris) tos organizacijos koordinatoriumi.

**Comment by adp-atea** [comment]
Ištestuota. Ataskaita prisegama. 

[Klaidu-patikra-0123.pdf](https://github.com/user-attachments/files/18531521/Klaidu-patikra-0123.pdf)

**Comment by rugile-domeikaite** [comment]
Redaguojant duomenų rinkinį, 500 klaida, kiek matau susiję su šia užduotim. 

Log'as:
```
Internal Server Error: /datasets/2547/update/
Traceback (most recent call last):
  File "/opt/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/reversion/views.py", line 32, in do_revision_view
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 71, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 104, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/vitrina/datasets/views.py", line 761, in get
    return super(DatasetUpdateView, self).get(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/django/views/generic/edit.py", line 190, in get
    return super().get(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/django/views/generic/edit.py", line 133, in get
    return self.render_to_response(self.get_context_data())
                                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/vitrina/datasets/views.py", line 748, in get_context_data
    context = super().get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/parler/views.py", line 244, in get_context_data
    context = super().get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/django/views/generic/edit.py", line 66, in get_context_data
    kwargs['form'] = self.get_form()
                     ^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/django/views/generic/edit.py", line 33, in get_form
    return form_class(**self.get_form_kwargs())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/vitrina/datasets/forms.py", line 211, in __init__
    self.fields['publisher'].initial = representative.first().organization.pk
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'organization'
```

**Comment by adp-atea** [comment]
Ištestuota. Testavimo ataskaita prisegama. 

[Klaidu-patikra-0221.pdf](https://github.com/user-attachments/files/18906663/Klaidu-patikra-0221.pdf)
