### ISSUE TITLE
Rinkinio modelių sąrašas

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#288]
Duomenų struktūros peržiūros puslapyje rodyti ne visą struktūros išklotinę, bet pirmiausia rodyti tik modelių sąrašą, kuris turėtu atrodyti taip:

![image](https://user-images.githubusercontent.com/297583/235154478-61165d61-20b0-45a9-a0ff-06fa2b9d091c.png)

Kiekvienas sąrašo elementas turi rodyti:

- Modelio kodinį pavadinimą
- Modelio bazė, jei tokia yra. Rodant modelio bazę reikėtų rodyti tik modelio pavadinimą, be vardų erdvės.
- Nuorodą į ontologiją, jei ji pateikta.
- Modelio brandos lygį apskaičiuotą iš pačio modelio, modelio bazės ir visų modelio property brandos lygių, nurodytų level stulpelyje, imant vidurkį.
- Modelio pavadinimą, jei pavadinimo nėra, tada rodyti modelio aprašymo pirmus 8 žodžius.

Brandos modeliui turėtu būti apskaičiuojamas ne dinamiškai, pateikiant sąrašą, o importuojant struktūros aprašą arba keičiant metaduomenis. T.y. jei keičiam modelio property arba pačio modelio metaduomenis, jei keičiasi brandos lygis jis turi būti apskaičiuotas ir išsaugotas prie modelio, metaduomenų keitimo metu.

**URL**: `/datasets/{dataset.id}/models/`

Pakeičia `/datasets/{dataset.id}/structure/`.

### Epic

- #15 

### Priklauso nuo

- https://github.com/atviriduomenys/katalogas/issues/290

**Comment by sirex** [comment]
![Image](https://github.com/atviriduomenys/katalogas/assets/297583/81608982-7dea-469c-a4fe-909905d4e48d)

Nerodyti base ir uri, jei jie nepateikti.

**Comment by sirex** [comment]
![Image](https://github.com/atviriduomenys/katalogas/assets/297583/4a1984ae-01e8-4715-939b-a5fd30a512e2)

Modelio pavadinimas neturi užlipti and base/uri, base ir uri reikėtų rodyti ne kaip stulpelė, o iš karto po modelio pavadinimo.

Modelio title, turi būti rodomas per visą ilgį, nes tokiu tikslu pavadinimas ir rodomas atskiroje eilutėje, nes pavadinimai gali būti gan ilgi.

**Comment by sirex** [comment]
Peržiūrint modelių sąrašą prisijungusio, tačiau tvarkytojo teisių neturinčio naudotojo teisėmis, gaunu:

![Image](https://github.com/atviriduomenys/katalogas/assets/297583/2f9ca39f-a993-4803-8063-64dab74c8395)


```python
Traceback (most recent call last):
  File "vitrina/templatetags/comment_tags.py", line 21, in comments
    perm = has_perm(user, Action.COMMENT, obj)
  File "vitrina/orgs/services.py", line 107, in has_perm
    nodes = get_parents(obj)
  File "vitrina/orgs/services.py", line 80, in get_parents
    return obj.get_acl_parents()
Exception Type: AttributeError at /datasets/1670/models/
Exception Value: 'DatasetStructure' object has no attribute 'get_acl_parents'
```

**Comment by sirex** [comment]
Paspaudus ant „Duomenys“ gaunu nuorodą į

    /datasets/1670/models/None/

**Comment by sirex** [comment]
![Image](https://github.com/atviriduomenys/katalogas/assets/297583/c4d67728-16b6-4e07-82e9-52b6e7d83c63)

Šiuo mygtukus turi rodyti tik duomenų rinkinio tvarkytojams.

**Comment by sirex** [comment]
Modelių sąrašas turi būti surūšiuotas pagal modelio kodinio pavadinimą, abėcėlės tvarka.

**Comment by sirex** [comment]
![Image](https://github.com/atviriduomenys/katalogas/assets/297583/ddcd8f45-bf89-4dbb-91bb-5d9de2864ab6)

Meniu turėtu būti išdėstytas tokia tvarka:

- Informacija
- Struktūra
- Duomenys
- Projektai
- Tvarkytojai
- Istorija

**Comment by sirex** [comment]
Super adminui ir duomenų rinkinio tvarkytojui rodome visus modelius, tačiau visiems kitiems rodome tik `access` = `open` ir `public` modelius. Tas pats galioja ir duomenų laukams ir komentarams.

Modelio `access` yra išskaičiuojamas iš `model.properties`. `model.access` yra lygus aukščiausiam `property.access`. Tai reiškia, kad jie yra bent vienas property, kurio `access` yra `open`, tai ir modelis yra `open`. Jei nėra nei vieno open property, bet yra vienas public property, tada model.access yra `public`. Atitinkamai ir su kitais access lygiais.

https://atviriduomenys.readthedocs.io/dsa/access.html

**Comment by sirex** [comment]
```
Page not found (404)
No Model matches the given query.
Request Method:	GET
Request URL:	http://localhost:8000/datasets/1200/models/AllServiceStatusReport/
Raised by:	vitrina.structure.views.ModelStructureView
```

Ši klaida tikriausiai susijusi su teisėmis. Nors sąraše modelis rodomas, tačiau paspaudus ant jo, meta 404 klaidą. Čia yra modelis, kuris neturi užpildyto nei vieno `access`, ko pasekoje, modelio access tampa `private`. Jo neprisijungusiam naudotojui iš vis neturėtu rodyti.

Tačiau, jei prisijungiu, kaip super administratorius, gaunu tą pačią klaidą.

**Comment by sirex** [comment]
Iš pradžių bandžiau suimportuoti tokį struktūros aprašą:

[adk.csv](https://github.com/atviriduomenys/katalogas/files/11622048/adk.csv)

Į http://localhost:8000/datasets/1223/models/ duomenų rinkinį, per `Importuoti` mygtuką. Susiimportavo gerai.

Tačiau, po to bandžiau importuoti ant viršaus kitą, to pačio struktūros aprašo versiją:

[data.gov.lt.csv](https://github.com/atviriduomenys/katalogas/files/11622063/data.gov.lt.csv)

Tačiau importas truko gal 5 minutes, su 100% CPU apkrovimu ir panaudojant kelis GB RAM. Palaukęs penkias minutes perkroviau serverį, nes struktūros aprašo importas tiek laiko negali trukti. Struktūros apraše yra vos 715 eilutės, todėl manau, kad yra kažkokia klaida importo mechanizme.

**Comment by sirex** [comment]
Po struktūros aprašo import susikuria po atskirą `resource` kiekvienam modeliui, nors turėtu susikurti tik vienas `resource` įrašas, kiekvienai struktūros apraše esančiai `resource` eilutei. Jei struktūros apraše nėra `resource`, tada turi susikurti vienas `resource` duomenų rinkiniui su nuoroda į `https://get.data.gov.lt/datasets/gov/org/dataset/:ns`.

**Comment by sirex** [comment]
> Iš pradžių bandžiau suimportuoti tokį struktūros aprašą:
> 
> [adk.csv](https://github.com/atviriduomenys/katalogas/files/11622048/adk.csv)
> 
> Į http://localhost:8000/datasets/1223/models/ duomenų rinkinį, per `Importuoti` mygtuką. Susiimportavo gerai.
> 
> Tačiau, po to bandžiau importuoti ant viršaus kitą, to pačio struktūros aprašo versiją:
> 
> [data.gov.lt.csv](https://github.com/atviriduomenys/katalogas/files/11622063/data.gov.lt.csv)
> 
> Tačiau importas truko gal 5 minutes, su 100% CPU apkrovimu ir panaudojant kelis GB RAM. Palaukęs penkias minutes perkroviau serverį, nes struktūros aprašo importas tiek laiko negali trukti. Struktūros apraše yra vos 715 eilutės, todėl manau, kad yra kažkokia klaida importo mechanizme.

Importavus tą patį struktūros aprašą, gaunu klaidą:

![image](https://github.com/atviriduomenys/katalogas/assets/297583/d842ae33-870b-412a-9f9b-088b9dac06e5)

Nors tokios klaidos neturėtu būti. Turėtu būti patikrinama var vardų erdvė sutampa su organizacijos ir duomenų rinkinio kodiniu pavadinimu. Jei prie organizacijos ir prie rinkinio dar nėra kodinio pavadinimo lauko, tai jie turėtu būti pridėti.

**Comment by sirex** [comment]
Importuojant struktūros aprašą, kuris saugomas Saugykloje ir toks duomenų šaltinis (distribucija) jau yra sąraše, sukuriama antra distribucija, su ta pačia nuoroda.

![image](https://github.com/atviriduomenys/katalogas/assets/297583/fcd44290-e845-4136-af90-192f2339618a)

Tačiau importuojant tą patį strukūros aprašą antrą kartą, tečia distribucija nesusikuria.

Abiejų distribucijų URL yra vienodas:

    https://get.data.gov.lt/datasets/gov/vat/sert_bulv/:ns
    https://get.data.gov.lt/datasets/gov/vat/sert_bulv/:ns

Be to, jei importuojant struktūros aprašą nėra šaltinio, turi būti parenkamas „Saugyklos API“ formatas.

Bandžiau importuoti https://github.com/atviriduomenys/manifest/blob/master/datasets/gov/vat/r19_sertif_bulv.csv

Į http://localhost:8000/datasets/1875/

**Comment by sirex** [comment]
Greičiausiai dėl to, kad importuojant distribucijas, nenurodomas formatas, gaunu tokias klaidas:

```python
Traceback (most recent call last):
  File "django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]
TypeError: 'Dataset' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "vitrina/datasets/models.py", line 197, in formats
    return [str(obj.get_format()).upper() for obj in self.datasetdistribution_set.all() if obj.get_format()]
  File "vitrina/datasets/models.py", line 197, in <listcomp>
    return [str(obj.get_format()).upper() for obj in self.datasetdistribution_set.all() if obj.get_format()]
TypeError: __str__ returned non-string (type NoneType)
```

**Comment by sirex** [comment]
> Greičiausiai dėl to, kad importuojant distribucijas, nenurodomas formatas, gaunu tokias klaidas:
> 
> ```python
> Traceback (most recent call last):
>   File "django/template/base.py", line 829, in _resolve_lookup
>     current = current[bit]
> TypeError: 'Dataset' object is not subscriptable
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "vitrina/datasets/models.py", line 197, in formats
>     return [str(obj.get_format()).upper() for obj in self.datasetdistribution_set.all() if obj.get_format()]
>   File "vitrina/datasets/models.py", line 197, in <listcomp>
>     return [str(obj.get_format()).upper() for obj in self.datasetdistribution_set.all() if obj.get_format()]
> TypeError: __str__ returned non-string (type NoneType)
> ```

Pasirodo tokia klaida atsiranda todėl, kad kažkas sukuria `Format` objektą su `title = None`. String tipas praktiškai niekada neturi būti nullable, nebent tam yra rimta priežastis. Reikėtų pakeisti, kas `Format.title` yra `null = False`.
