### ISSUE TITLE
Modelio duomenų peržiūra

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#300]
URL: `/datasets/{id}/data/{model}?select(name, country)&population>1000&sort(-population)`.

![image](https://user-images.githubusercontent.com/297583/235994955-9f85e8cd-82ae-415f-9876-86180829435e.png)

Atvaizduojant duomenis, daroma užklausa į Saugyklą (get.data.gov.lt) ir rezultatas atvaizduojamas lentelėje.

- [x] Paspaudus ant lentelės stulpelio (duomenų lauko) pavadinimo, patenkama į Struktūra dalį, duomenų lauko peržiūros langą.
- [x] Paspaudus ant lentelės stulpelio (duomenų lauko) tipo, kai tipas yra `ref`, patenkama į siejamo modelio duomenų peržiūrą.
- [x] Paspaudus ant `_id` arba ant `ref` tipo reikšmės, patenkama į vieno objekt peržiūros langą.
- [x] Paspaudus ant ▼ simbolio, atsidaro langas, kuriame galima nurodyti filtrą, rūšiavimo tvarką arba paslėpti konkretų lauką.
- [x] Paspaudus ant Struktūra, patenkama į aktyvaus modelio peržiūrą.
- [x] Virš lentelės rodomas aktyvus filtras.
- [x] Filtro `select()` atveju, rodomas iškrentantis sąrašas, kuriame galima pasirinkti, kokius laukus rodyti.
- [x] Paspaudus ⮿ simbolį ant aktyvaus filtro, filtras pašalinamas.
- [x] `integer` ir `number` tipo duomenys lygiuojami dešinėje pusėje.
- [ ] Jei duomenų laukas turi `unique` žymę, rodomas rakto simbolis.
- [x] Rodoma ne daugiau nei 100 objektų, tai reiškia, kad darant užklausą į Saugyklą, visada nurodoma `limit(100)`.
- [x] Adreso juostoje `{model}` yra modelio pavadinimas reliatyvus duomenų rinkinio pavadinimui. Tai reiškia, kad adrese rodome `City`, o ne `datasets/gov/rc/ar/City`.
- [x] Galimi filtravimo operatoriai:
    - [x] `=`
    - [x] `>`
    - [x] `<`
    - [x] `>=`
    - [x] `<=`
    - [x] `contains`
    - [x] `startswith`
    - [x] `endswith`

### Epic

- https://github.com/atviriduomenys/katalogas/issues/56

### Susiję

- https://github.com/atviriduomenys/katalogas/issues/301

**Comment by sirex** [comment]
Jei nėra jokių duomenų, tada reikia rodyti pranešimą, kad duomenų nėra, dabar rodo tai:



![Image](https://github.com/atviriduomenys/katalogas/assets/297583/1d5d52ad-70f3-4baa-a4bb-b876f635b9e1)


Atsisiuntimo iškrentantis sąrašas neveikia, rodo keistai tik _id lauką.

**Comment by sirex** [comment]
![Image](https://github.com/atviriduomenys/katalogas/assets/297583/5b5f6919-1afe-45b6-86af-58902a93d6fe)

Reikėtų rodyti, kaip iškrentantį sąrašą, panašiai, kaip mygtukas „Atsisiųsti“.

**Comment by sirex** [comment]
Užpildžius filtro formą:



![Image](https://github.com/atviriduomenys/katalogas/assets/297583/d5aa8a36-70f7-4f3d-826c-f82cc80e1107)


Ir paspaudus filtruoti, gaunu tokią klaidą:

> Unexpected token Token('NAME', 'r') at line 1, column 39. Expected one of: * LPAR * $END * VBAR * DOT * COMMA * COMP * FACTOR * AMPERSAND * TERM * LSQB Previous tokens: [Token('NAME', 'Vilniaus')]

Kaip suprantu, klaida susijusi su tuo, kad neuždedamos kabutės ant filtro reikšmės, nes nukreipimas daromas į tokį URL:

    ?municipality_name=Vilniaus%20r.%20sav.

O turėtu būti

    ?municipality_name="Vilniaus%20r.%20sav."

Kabutes reikia uždėti string ir date tipo laukams.

**Comment by sirex** [comment]
![Image](https://github.com/atviriduomenys/katalogas/assets/297583/effa6d76-db05-4e79-bfb2-63ccfeba27bd)

Nerodo horizontalios slinkties juostos. Duomenų lentelė turi būti įdėta į div, kuris turi vertikalią slinkties juostą (scrollbar), jei duomenys netelpa horizontaliai.

**Comment by sirex** [comment]
Atsisiunčiant duomenis  CSV ar kitu formatu, neturi būti taikomas `limit`, nes `limit` taikomas tik atvaizduojant duomenis html formatu.

Dabar formuojama tokia nuoroda duomenų atsisiuntimui:


    https://get.data.gov.lt/datasets/gov/lsd/covid19/AtvejaiIrMirtys?limit(100)&format(csv)

Nors turėtu būti:

    https://get.data.gov.lt/datasets/gov/lsd/covid19/AtvejaiIrMirtys?format(csv)

**Comment by sirex** [comment]
Nežinau dėl kokių priežasčių, bet modelio duomenų peržiūros puslapį, krauna beveik 5 sekundes, kas yra nepriimtinai lėtai. Patikrinau, ta pati lentelė saugykloje išvedama per pusę sekundės, tai reiškia katalogo pusėje yra 4.5 sekundės labai neefektyvaus kodo.

**Comment by sirex** [comment]
Request Method: GET
Request URL: http://localhost:8000/datasets/1223/models/Organization/

Django Version: 3.2.16
Python Version: 3.10.10

```
Traceback (most recent call last):
  File "vitrina/structure/models.py", line 75, in uri_link
    prefix, name = self.uri.split(':', 1)

Exception Type: ValueError at /datasets/1223/models/Organization/
Exception Value: not enough values to unpack (expected 2, got 1)
```

Čia tokia klaida atsiranda bandant užkrauti https://github.com/atviriduomenys/manifest/blob/master/datasets/gov/ivpk/adk.csv

Kuriame, prie `Organization.description` yra nurodyta `uri: dct.description`. Užkraunant duomenis reikėtų patikrinti ar yra nurodytas `uri` prefiksas ir jei jis nenurodytas tada mesti klaidą. Į `uri` stulpelį galima įrašyti URI su prefiksu, arba pilna forma `https://...`, be prefikso. Tai siūlau patikrinti ar `uri` yra `://` arba `:`. Jei yra `://` reiškia URI yra pilnas, jei yra tik `:`, reiškia URI yra su prefiksu, jei nėra nei `://`, nei `:`, tada klaida.

Ir atvaizduojant URI metaduomenis, reikėtų įvertinti, kad gali būti URI pilnas ir su prefiksu.

Jei yra nurodytas prefiksas, jis turi būti apibrėžtas prie duomenų rinkinio.

**Comment by sirex** [comment]
Šoninėje juostoje, modelių sąrašas turi būti surūšiuotas pagal modelio kodinį pavadinimą, abėcėlės tvarka.

**Comment by sirex** [comment]
![Image](https://github.com/atviriduomenys/katalogas/assets/297583/c6f2ebdc-c0d4-4b89-8eac-5cacbc31f247)


Filtro mygtukas, prie duomenų lauko neturėtų persikelti į naują eilutę.

**Comment by sirex** [comment]
![Image](https://github.com/atviriduomenys/katalogas/assets/297583/9e0355e0-3a97-4ce7-bc27-10c323d1498f)

Checkbox ir lauko pavadinimas turėtu išlikti vienoje eilutėje.

**Comment by sirex** [comment]
![Image](https://github.com/atviriduomenys/katalogas/assets/297583/3c41fb16-27b5-42a8-ab28-8622f69fe87d)

Paspaudus ant select() checkbox, sąrašas neturėtu iš karto užsidaryti, turėtu leisti pasirinkti kitus laukus. Pasirinkimai turi būti rodomi paspaudus mygtuką „Rodyti“, kuris yra iškrentančio sąrašo apačioje.

Dabar kai yra daugiau laukų, labai sudėtinga daryti atranką, nes kiekvieną kartą pasirinkus lauką, sąrašas užsidaro ir puslapis persikrauna. Jei nori pažymėti 10 laukų, tai padaryti labai sudėtinga, kai kiekvienas paspaudimas perkrauna puslapį.

**Comment by sirex** [comment]
Operatorių sąraše trūksta `!=` operatoriaus.

Ir dar viena problema. Dabar padaryta, kad įrašius filtro reikšmę, `string` tipui automatiškai uždedamos kabutės. Tačiau reikia padaryti išimtį, jei įrašoma `null` reikšmė, tada kabučių uždėti nereikia. Tačiau jei įrašyta `"null"` su kabutėmis, tada taip ir siųsti, t.y. atlikti paiešką tekstui `"null"`, t.y. nereikia uždėti dar vienų kabučių.

**Comment by sirex** [comment]
![Image](https://github.com/atviriduomenys/katalogas/assets/297583/f2dc9414-472e-4dd4-a8c8-93ce4a836cf8)

Jei filtre įvedu kabutes, gaunu klaidą:

No terminal matches '"' in the current parser context, at line 1 col 17 limit(100)&name=""" ^ Expected one of: * STRING * ALL * LPAR * NAME * SIGN * BOOL * INT * FLOAT * LSQB Previous tokens: Token('COMP', '=')

Reikėtų prieš visas kabutes pridėti `\` simbolį, kad būtų `\"`, tokiu būdu klaidos nebus.

**Comment by sirex** [comment]
Atlikus paiešką su filtru, jei nerandami jokie duomenys, tada nerodo pasirinktų filtrų ir nėra galimybės jų pakeisti ar pašalinti.



![Image](https://github.com/atviriduomenys/katalogas/assets/297583/8db7555e-c186-4a4a-99d1-7192a4abca14)


Jei duomenų neranda, turi rodyti aktyvius filtrus ir laukų sąrašą.



![Image](https://github.com/atviriduomenys/katalogas/assets/297583/fd5344e4-fae4-4ccd-b3fd-1f9b005c2531)


Tokiu būdu bus galima pataisyti filtrus, jei pagal ankstesnius filtrus nerasta jokių duomenų.

**Comment by sirex** [comment]
Ilgą tekstą apriboti iki 256 simbolių ir rodyti `...` jei tekstas buvo nukirptas.



![Image](https://github.com/atviriduomenys/katalogas/assets/297583/42e89e91-a039-435e-8fd8-83cd6ecfb9a5)

**Comment by sirex** [comment]
![Image](https://github.com/atviriduomenys/katalogas/assets/297583/b3b3dfdf-5c5e-490c-8def-948c28614356)

Paspaudus rodyklę į viršų, turi būti rūšiuojama Z -> A, paspaudus rodyklę žemyn turi rūšiuoti A -> Z. Dabar padaryta atvirkščiai, reikia sukeisti vietomis.

**Comment by sirex** [comment]
![Image](https://github.com/atviriduomenys/katalogas/assets/297583/e911313a-f38e-490e-afca-9db1ecab0d82)

Nerodom `None`, jei reikšmė yra `None`, tada celė turi būti tuščia ir su šviesiai pilku fonu.

**Comment by sirex** [comment]
![Image](https://github.com/atviriduomenys/katalogas/assets/297583/927c0ce0-2151-4c87-898f-72b21324ab12)

Jei modelis neturi `title`, rodom `name`.

**Comment by sirex** [comment]
![Image](https://github.com/atviriduomenys/katalogas/assets/297583/f594f98a-fd7a-4c5d-87fc-426cccf65f1d)

Nurodytoje vietoje reikia rodyti tokį tekstą:

> Rodoma 100 objektų iš 10,000.

Kur `100` yra objektų skaičius, kuris rodomas puslapyje, o `10,000` yra skaičius, kiek iš viso yra objektų, šį skaičių galima gauti darant `/Model?count()` užklausą į Saugyklą.

**Comment by sirex** [comment]
http://localhost:8000/datasets/1223/models/

```python
Traceback (most recent call last):
  File "vitrina/structure/models.py", line 180, in get_absolute_url
    return reverse('model-structure', kwargs={
  File "django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "django/urls/resolvers.py", line 698, in _reverse_with_prefix
    raise NoReverseMatch(msg)

Exception Type: NoReverseMatch at /datasets/1223/models/
Exception Value: Reverse for 'model-structure' with keyword arguments '{'pk': 1223, 'model': ''}' not found. 1 pattern(s) tried: ['datasets/(?P<pk>[0-9]+)/models/(?P<model>[^/]+)/\\Z']
```

Ta pati klaida pasitaiko ir su http://localhost:8000/datasets/1223/data/Catalog/

```python
Template error:
In template vitrina/structure/templates/vitrina/structure/side_menu.html, error at line 6
   Reverse for 'model-data' with keyword arguments '{'pk': 1223, 'model': ''}' not found. 1 pattern(s) tried: ['datasets/(?P<pk>[0-9]+)/data/(?P<model>[^/]+)/\\Z']
   1 : <nav class="category-panel">
   2 :     {% for model in models %}
   3 :         <div>
   4 :             <span class="has-tooltip-top" data-tooltip="{{ model.name }}">
   5 :                 {% if is_data %}
   6 :                     <a href=" {{ model.get_data_url }} " class="category-panel-block">
   7 :                 {% else %}
   8 :                     <a href="{{ model.get_absolute_url }}" class="category-panel-block">
   9 :                 {% endif%}
   10 : 
   11 :                 {% if not show_props and request.resolver_match.kwargs.model == model.name %}
   12 :                     <strong><span id="side_menu_elem">{{ model.name }}</span></strong>
   13 :                 {% else %}
   14 :                     <span id="side_menu_elem">{{ model.name }}</span>
   15 :                 {% endif %}
   16 :                 </a>


Traceback (most recent call last):
  File "vitrina/structure/models.py", line 186, in get_data_url
    return reverse('model-data', kwargs={
  File "django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "django/urls/resolvers.py", line 698, in _reverse_with_prefix
    raise NoReverseMatch(msg)

Exception Type: NoReverseMatch at /datasets/1223/data/Catalog/
Exception Value: Reverse for 'model-data' with keyword arguments '{'pk': 1223, 'model': ''}' not found. 1 pattern(s) tried: ['datasets/(?P<pk>[0-9]+)/data/(?P<model>[^/]+)/\\Z']
```

Turiu įtarimą, kad kažkas blogai su duomenimis, bet problema, kad negaliu iš naujo importuoti struktūros aprašo. Todėl būtų gerai, kad tokios klaidos neuždarytų kelio, struktūros aprašo importavimui.

Gali būti, kad tai yra susiję su

- https://github.com/atviriduomenys/katalogas/issues/288#issuecomment-1571445488
- https://github.com/atviriduomenys/katalogas/issues/288#issuecomment-1571474016

**Comment by sirex** [comment]
> ![Image](https://user-images.githubusercontent.com/297583/242475318-f594f98a-fd7a-4c5d-87fc-426cccf65f1d.png)
> 
> Nurodytoje vietoje reikia rodyti tokį tekstą:
> 
> > Rodoma 100 objektų iš 10,000.
> 
> Kur `100` yra objektų skaičius, kuris rodomas puslapyje, o `10,000` yra skaičius, kiek iš viso yra objektų, šį skaičių galima gauti darant `/Model?count()` užklausą į Saugyklą.

![image](https://github.com/atviriduomenys/katalogas/assets/297583/c46679a9-8c95-4c6b-a988-b0a1744c0849)

Turi rodyti „Rodoma 2 objektai iš 2.“, t.y. `count()` pridedamas su filtru.

Jei skaičius didelis, turi būti kablelis, kas tūkstanį.

Ir tekstas su skaičiais turėtu naudoti daugiskaitos/vienaskaitos formą: https://docs.djangoproject.com/en/4.2/topics/i18n/translation/#pluralization

**Comment by sirex** [comment]
![image](https://github.com/atviriduomenys/katalogas/assets/297583/1d74551e-e68a-4b46-9c00-bcc1eb6800ca)

Jei nėra rezultatų, filtras pasislepia.

http://localhost:8000/datasets/389/data/Atkn1TendererGroupList/?group_name=%22aa%22
