### ISSUE TITLE
Rodiklių vizualizacija laike

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#316]
Duomenų rinkinių sąraše, pasirinkus laikotarpį, atvaizduoti pasirinkto rodiklio grafiką pagal pasirinktą laikotarpį.

![image](https://github.com/atviriduomenys/katalogas/assets/297583/9768ccf1-5e81-4162-a0e4-f1b81f841fe2)

Jei, duomenų rinkinių sąrašas filtruojamas pagal būsenos, valdymo srities, kategorijos ar kitus filtrus, atitinkamai tai turi atsispindėti ir laiko juostos grafike.

Pasirinkus kitą rodiklį, laiko juostos y ašyje turi būti atitinkamai atvaizduojami rodiklio įverčiai. x ašyje turi būti laiko skalė.

Atvaizduoti visus rodiklius, kurie paminėti #299 užduotyje.

### Epic

- https://github.com/atviriduomenys/katalogas/issues/19

**Comment by sirex** [comment]
https://test.data.gov.lt/datasets/stats/status/?

```python
Internal Server Error: /datasets/stats/status/
Traceback (most recent call last):
  File "django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "haystack/generic_views.py", line 130, in get
    return self.form_valid(form)
  File "haystack/generic_views.py", line 77, in form_valid
    context = self.get_context_data(
  File "vitrina/datasets/views.py", line 1381, in get_context_data
    'label': str(status_translations[status]),
KeyError: 'UNASSIGNED'
```
