### ISSUE TITLE
MP node organizacijai sutvarkymas

### ISSUE THREAD

**Issue by Faustasm** [atviriduomenys/katalogas#369]
https://github.com/atviriduomenys/katalogas/blob/devel/vitrina/orgs/migrations/0003_auto_20220829_0841.py
Ar tikrai migracija viska sutvarko?
Kviečiant add_root (su migracijom tuščioj db) -> objektas sukuriamas
Kviečiant add_root (su migracijom ir importuotais duomenim ) -> gaunamas key constraint erroras

**Comment by sirex** [comment]
Pateiktoje nuorodoje nėra `call_root` pavadinimo, gal galima gauti pilną klaidos traceback?

**Comment by Faustasm** [comment]
> Pateiktoje nuorodoje nėra `call_root` pavadinimo, gal galima gauti pilną klaidos traceback?

Pataisiau: kviečiamas add_root:

> `>>> new_org = Organization.add_root(title='testorg', company_code='5467-54678', slug='tea')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/faustas/.cache/pypoetry/virtualenvs/vitrina-7JRhvVf8-py3.10/lib/python3.10/site-packages/treebeard/mp_tree.py", line 623, in add_root
    return MP_AddRootHandler(cls, **kwargs).process()
  File "/home/faustas/.cache/pypoetry/virtualenvs/vitrina-7JRhvVf8-py3.10/lib/python3.10/site-packages/treebeard/mp_tree.py", line 319, in process
    return last_root.add_sibling('sorted-sibling', **self.kwargs)
  File "/home/faustas/.cache/pypoetry/virtualenvs/vitrina-7JRhvVf8-py3.10/lib/python3.10/site-packages/treebeard/mp_tree.py", line 1106, in add_sibling
    return MP_AddSiblingHandler(self, pos, **kwargs).process()
  File "/home/faustas/.cache/pypoetry/virtualenvs/vitrina-7JRhvVf8-py3.10/lib/python3.10/site-packages/treebeard/mp_tree.py", line 422, in process
    siblings = self.node.get_sorted_pos_queryset(
  File "/home/faustas/.cache/pypoetry/virtualenvs/vitrina-7JRhvVf8-py3.10/lib/python3.10/site-packages/treebeard/models.py", line 570, in get_sorted_pos_queryset
    return siblings.filter(reduce(operator.or_, filters))
  File "/home/faustas/.cache/pypoetry/virtualenvs/vitrina-7JRhvVf8-py3.10/lib/python3.10/site-packages/django/db/models/query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/faustas/.cache/pypoetry/virtualenvs/vitrina-7JRhvVf8-py3.10/lib/python3.10/site-packages/django/db/models/query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/faustas/.cache/pypoetry/virtualenvs/vitrina-7JRhvVf8-py3.10/lib/python3.10/site-packages/django/db/models/query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/faustas/.cache/pypoetry/virtualenvs/vitrina-7JRhvVf8-py3.10/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1416, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/faustas/.cache/pypoetry/virtualenvs/vitrina-7JRhvVf8-py3.10/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1435, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/faustas/.cache/pypoetry/virtualenvs/vitrina-7JRhvVf8-py3.10/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1288, in build_filter
    return self._add_q(
  File "/home/faustas/.cache/pypoetry/virtualenvs/vitrina-7JRhvVf8-py3.10/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1435, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/faustas/.cache/pypoetry/virtualenvs/vitrina-7JRhvVf8-py3.10/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1288, in build_filter
    return self._add_q(
  File "/home/faustas/.cache/pypoetry/virtualenvs/vitrina-7JRhvVf8-py3.10/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1435, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/faustas/.cache/pypoetry/virtualenvs/vitrina-7JRhvVf8-py3.10/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1370, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/faustas/.cache/pypoetry/virtualenvs/vitrina-7JRhvVf8-py3.10/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1221, in build_lookup
    raise ValueError("Cannot use None as a query value")
ValueError: Cannot use None as a query value
>>> new_org = Category.add_root(title='testcat', featured=False)
>>> new_org = Organization.add_root(title='testorg', company_code='5467-54678', slug='tea')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/faustas/.cache/pypoetry/virtualenvs/vitrina-7JRhvVf8-py3.10/lib/python3.10/site-packages/treebeard/mp_tree.py", line 623, in add_root
    return MP_AddRootHandler(cls, **kwargs).process()
  File "/home/faustas/.cache/pypoetry/virtualenvs/vitrina-7JRhvVf8-py3.10/lib/python3.10/site-packages/treebeard/mp_tree.py", line 319, in process
    return last_root.add_sibling('sorted-sibling', **self.kwargs)
  File "/home/faustas/.cache/pypoetry/virtualenvs/vitrina-7JRhvVf8-py3.10/lib/python3.10/site-packages/treebeard/mp_tree.py", line 1106, in add_sibling
    return MP_AddSiblingHandler(self, pos, **kwargs).process()
  File "/home/faustas/.cache/pypoetry/virtualenvs/vitrina-7JRhvVf8-py3.10/lib/python3.10/site-packages/treebeard/mp_tree.py", line 422, in process
    siblings = self.node.get_sorted_pos_queryset(
  File "/home/faustas/.cache/pypoetry/virtualenvs/vitrina-7JRhvVf8-py3.10/lib/python3.10/site-packages/treebeard/models.py", line 570, in get_sorted_pos_queryset
    return siblings.filter(reduce(operator.or_, filters))
  File "/home/faustas/.cache/pypoetry/virtualenvs/vitrina-7JRhvVf8-py3.10/lib/python3.10/site-packages/django/db/models/query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/faustas/.cache/pypoetry/virtualenvs/vitrina-7JRhvVf8-py3.10/lib/python3.10/site-packages/django/db/models/query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/faustas/.cache/pypoetry/virtualenvs/vitrina-7JRhvVf8-py3.10/lib/python3.10/site-packages/django/db/models/query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/faustas/.cache/pypoetry/virtualenvs/vitrina-7JRhvVf8-py3.10/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1416, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/faustas/.cache/pypoetry/virtualenvs/vitrina-7JRhvVf8-py3.10/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1435, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/faustas/.cache/pypoetry/virtualenvs/vitrina-7JRhvVf8-py3.10/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1288, in build_filter
    return self._add_q(
  File "/home/faustas/.cache/pypoetry/virtualenvs/vitrina-7JRhvVf8-py3.10/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1435, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/faustas/.cache/pypoetry/virtualenvs/vitrina-7JRhvVf8-py3.10/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1288, in build_filter
    return self._add_q(
  File "/home/faustas/.cache/pypoetry/virtualenvs/vitrina-7JRhvVf8-py3.10/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1435, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/faustas/.cache/pypoetry/virtualenvs/vitrina-7JRhvVf8-py3.10/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1370, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/faustas/.cache/pypoetry/virtualenvs/vitrina-7JRhvVf8-py3.10/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1221, in build_lookup
    raise ValueError("Cannot use None as a query value")
ValueError: Cannot use None as a query value`
Su kitais modeliais viskas ok, problema atsikartojo tik su org. Leidau su indexuota db, migracijos padarytos.

**Comment by Faustasm** [comment]
Problemos nėra kviečiant fix_mp:
https://github.com/atviriduomenys/katalogas/pull/502/files#diff-050802123f78e55cc7511ee47f3bf8036298029cb70fc53f1cf6f3a3b3063cf9R442
