### ISSUE TITLE
Neveikia /datasets

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#577]
```python
Internal Server Error: /datasets/
Traceback (most recent call last):
  File "django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "haystack/generic_views.py", line 130, in get
    return self.form_valid(form)
  File "haystack/generic_views.py", line 77, in form_valid
    context = self.get_context_data(
  File "vitrina/datasets/views.py", line 150, in get_context_data
    date_facets = context['facets']['dates']
KeyError: 'dates'
```

Klaida pasireiškia neprisijungusiems naudotojams.

Būtina parašyti testą, kuri atkartoja klaidą. Kad ateityje tokio pobūdžio klaidų nebūtų.

**Comment by adp-atea** [comment]
Pakeičiau kaip paimamas date facet laukas ir parašiau pora testų su neprisijungusiu vartotoju, tačiau klaidos atkartoti nepavyko, nes viskas veikia korektiškai lokalioj aplinkoj ir su dabartiniu facet lauko paėmimu ir senu. Verta paminėti, kad ši klaida atsiranda tikriausiai dėl neatlikto rebuild_index.

**Comment by sirex** [comment]
`rebuild_index` yra paleistas, jis daromas po kiekvieno atnaujinimo. Jei būtų indekso problema, tai tikriausiai neveiktu ir su prisijungusiu naudotoju.

Po atnaujinimo gaunu naują klaidą:

```python
Traceback (most recent call last):
  File "haystack/backends/elasticsearch_backend.py", line 585, in search
    raw_results = self.conn.search(
  File "elasticsearch/client/utils.py", line 139, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "elasticsearch/client/__init__.py", line 1479, in search
    return self.transport.perform_request(
  File "elasticsearch/transport.py", line 345, in perform_request
    status, headers_response, data = connection.perform_request(
  File "elasticsearch/connection/http_urllib3.py", line 256, in perform_request
    self._raise_error(response.status, raw_data)
  File "elasticsearch/connection/base.py", line 287, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.RequestError:
    RequestError(400, 'search_phase_execution_exception', 'Failed to parse query [django_id:(
        "2" OR
        "3" OR
        "4" OR
        [...]  (1525 items ommited)
        "2350" OR
        "2355" OR
        "2356"
    )]')
Internal Server Error: /datasets/
Traceback (most recent call last):
  File "django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "django/template/defaulttags.py", line 170, in render
    values = list(values)
  File "vitrina/helpers.py", line 99, in items
    facet = fields[self.name]
TypeError: 'NoneType' object is not subscriptable
```

ElasticSearch loguose matau tokias žinutes:

```
Caused by: org.apache.lucene.queryparser.classic.ParseException: Cannot parse:
    django_id:(
        "2" OR
        "3" OR
        "4" OR
        [...]  (1525 items ommited)
        "2350" OR
        "2355" OR
        "2356"
    )'
too many boolean clauses.
```

Jei bandoma į vieną ElasticSearch užklausą sudėti visų duomenų rinkinių ID į vieną didelę OR seką, tai anksčiau ar vėliau ir turėjo nustoti veikit.
