### ISSUE TITLE
Klaida poreikio organizacijų sąraše

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#684]
https://data.gov.lt/requests/18/ - paspaudus ant „Organizacijos“ gaunu tokią klaidą:

```python
Internal Server Error: /requests/18/orgs/
Traceback (most recent call last):
  File "django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column vitrina_requests_requestassignment.created does not exist
LINE 1: ...", "vitrina_requests_requestassignment"."status", "vitrina_r...
                                                             ^
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "django/template/defaulttags.py", line 314, in render
    if match:
  File "django/db/models/query.py", line 284, in __bool__
    self._fetch_all()
  File "django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column vitrina_requests_requestassignment.created does not exist
LINE 1: ...", "vitrina_requests_requestassignment"."status", "vitrina_r...
```

**Comment by sirex** [comment]
Vis dar gaunu tą pačią klaidą,  @Faustasm būtų gerai, jai būtų ištestuota ar pataisymas tikrai veikia.

**Comment by sirex** [comment]
Vis dar gaunu tą pačią klaidą:

Iš https://test.data.gov.lt/requests/14366/ paspaudžiu ant „Organizacijos“ ir gaunu 500 klaidą.

Tiesioginė nuorodą į puslapį, kuris grąžinta 500 klaidą:

https://test.data.gov.lt/requests/14366/orgs/
