### ISSUE TITLE
Klaida importuojant GRPK struktūros aprašą

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#685]
Bandant importuoti [GRPK](https://github.com/atviriduomenys/manifest/blob/master/datasets/gov/giscentras/grpk.csv) struktūros aprašą, gaunu tokią klaidą:

https://data.gov.lt/datasets/1302/structure/import/

```python
Internal Server Error: /datasets/1302/structure/import/
Traceback (most recent call last):
  File "django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(255)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "vitrina/datasets/views.py", line 787, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "django/contrib/auth/mixins.py", line 71, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "django/contrib/auth/mixins.py", line 104, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "django/views/generic/edit.py", line 172, in post
    return super().post(request, *args, **kwargs)
  File "django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "vitrina/datasets/views.py", line 811, in form_valid
    create_structure_objects(self.object)
  File "vitrina/structure/services.py", line 59, in create_structure_objects
    _load_models(state, structure.dataset)
  File "vitrina/structure/services.py", line 279, in _load_models
    model, metadata = _create_or_update_metadata(dataset, meta, model, i)
  File "vitrina/structure/services.py", line 458, in _create_or_update_metadata
    metadata = Metadata.objects.create(
  File "django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: value too long for type character varying(255)
```

**Comment by adp-atea** [comment]
Pakeičiau metadata.title lauką iš varchar į text, pažiūrėk šitą. Čia vistiek šitas nėra itin degantis. Realiai bugas išlenda, jeigu dataseto title yra daugiau nei 255 simboliai.
