### ISSUE TITLE
Server error on model page

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#752]
https://test.data.gov.lt/datasets/1883/models/

```python
Internal Server Error: /datasets/1883/models/
Traceback (most recent call last):
  File "vitrina/templatetags/comment_tags.py", line 49, in comments
    'comment_form': comment_form_class(obj, auto_id='id_new_comment_%s_' + str(obj.pk)),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "vitrina/comments/forms.py", line 28, in __init__
    self.fields['body'].label = _("Komentaro tekstas objektui: ") + " " + str(obj)
                                                                          ^^^^^^^^
  File "vitrina/datasets/models.py", line 716, in __str__
    if self.dataset.metadata.first().title:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'title'
```

**Comment by adp-atea** [comment]
Panašu, kad klaida jau buvo pataisyta.
