### ISSUE TITLE
CSV preview UnicodeDecodeError

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#782]
https://data.gov.lt/datasets/1967/preview/10716/

```python
Traceback (most recent call last):
  File "vitrina/datasets/views.py", line 416, in get
    data = list(csv.reader(rows, delimiter=";"))
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 52: invalid continuation byte
```

XLSX failą bandoma atidaryti, kaip CSV failą. Bet taip pat, tame pačiame duomenų rinkinyje, atidarant ir CSV failą, gaunama ta pati unicode klaida.

Be to, preview atveju, neturėtu būti į atmintį užkraunamas visas failas, reikėtu nuskaityti tik kelias eilutes.

**Comment by adp-atea** [comment]
Uzdejau, kad rodytu penkias pirmas penkias eilutes

**Comment by Faustasm** [comment]
XLSX Testavimui:
https://test.data.gov.lt/datasets/1138/#info
https://test.data.gov.lt/datasets/1138/preview/8113/ 500 Klaida negrįžta, gaunami failo json, bet rodoma **JSON.PARSE k**laida. Matosi screenshote.
CSV Testavimui:
https://test.data.gov.lt/datasets/1604/#info
https://test.data.gov.lt/datasets/1604/preview/14041/ 500 Klaida negrįžta, gaunami failo json.

Spaudžiant peržiūrėti prie csv failo https://test.data.gov.lt/datasets/1604/#info, modalinis atsidaro ir matosi informacija.

Spaudžiant peržiūrėti prie xlsx failo https://test.data.gov.lt/datasets/1138/#info, modalinis atsidaro, duomenys nesimato. Tikriausiai del minėto JSON.PARSE erroro
<img width="945" alt="ss5" src="https://github.com/atviriduomenys/katalogas/assets/30083780/0e232591-6eaa-475e-b78e-5bf3bba518f4">

**Comment by sirex** [comment]
Klaida vis dar neišspręsta, atidarius https://test.data.gov.lt/datasets/2309/preview/13962/

Gaunu:

```python
Traceback (most recent call last):
  File "django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "vitrina/datasets/views.py", line 449, in get
    data = list(csv.reader(rows, delimiter=";"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 595: invalid start byte
```

**Comment by Faustasm** [comment]
Vis dar atsikartoja
