### ISSUE TITLE
Klaida duomenų šaltinio peržiūroje

### ISSUE THREAD

**Issue by Faustasm** [atviriduomenys/katalogas#811]
Atsikartoja spaudžiant "Peržiūrėti". Vartotojui klaida nerodoma, bet rodomas tuščias langas.

![Image](https://github.com/atviriduomenys/katalogas/assets/30083780/66c3041c-19bc-44c5-b199-44a4ea99ac29)

![Image](https://github.com/atviriduomenys/katalogas/assets/30083780/ff4ac87b-e2eb-4276-9983-946735ea2f53)

**Comment by Faustasm** [comment]
Internal Server Error: /datasets/<>/preview/<>/
|   File "<frozen codecs>", line 322, in decode
| UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 595: invalid start byte

**Comment by adp-atea** [comment]
Turėtų būti sutvarkyta su šituo task`u
https://github.com/orgs/atviriduomenys/projects/9/views/1?pane=issue&itemId=45110542

**Comment by sirex** [comment]
Vis dar nesutvarkyta, atidarius https://test.data.gov.lt/datasets/1138/preview/8116/

Gaunu:

```python
Traceback (most recent call last):
  File "django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "vitrina/datasets/views.py", line 444, in get
    raise "Not implemented for more than one value"
TypeError: exceptions must derive from BaseException
```

**Comment by adp-atea** [comment]
Su https://github.com/atviriduomenys/katalogas/pull/894
