### ISSUE TITLE
500 klaida importuojant struktūros aprašą

### ISSUE THREAD

**Issue by aurjas** [atviriduomenys/katalogas#850]
Importuojant struktūros aprašą gaunama klaida 500. Pridedu struktūros aprašus

[ambulatoriniai_apsilankymai.csv](https://github.com/atviriduomenys/katalogas/files/13613146/ambulatoriniai_apsilankymai.csv)

[stacionaro_apsilankymai.csv](https://github.com/atviriduomenys/katalogas/files/13613147/stacionaro_apsilankymai.csv)

Duomenų rinkiniai: https://data.gov.lt/datasets/2381/models/
                               https://data.gov.lt/datasets/2382/models/

Ta pati klaida abiems rinkiniams.

Traceback:
Internal Server Error: /datasets/2381/structure/import/
 Traceback (most recent call last):
   File "django/db/backends/utils.py", line 84, in _execute
     return self.cursor.execute(sql, params)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 psycopg2.errors.StringDataRightTruncation: value too long for type character varying(255)

     raise dj_exc_value.with_traceback(traceback) from exc_value
   File "django/db/backends/utils.py", line 84, in _execute
     return self.cursor.execute(sql, params)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 django.db.utils.DataError: value too long for type character varying(255)

**Comment by adp-atea** [comment]
Lokaliai abu failai susiimportuoja be klaidų. 

Panašu, kad klaida buvo dėl per ilgų `title`, tačiau ši vieta jau buvo taisyta seniau: `title` tipas pakeistas iš `CharField` į `TextField`.

**Comment by SauliusPetraitis** [comment]
Uždaroma kaip išspręsta (žr. ankstesnius komentarus – pataisyta / nebeaktualu). Jei vis dar pasikartoja, atidarykite iš naujo. (Katalogo issue higiena, 2026-07-01.)
