### ISSUE TITLE
Klaida 500: ištrinant vartotoją

### ISSUE THREAD

**Issue by IngaIVPK** [atviriduomenys/katalogas#981]
Atliekant šiuos veiksmus, meta 500 klaidą
https://data.gov.lt/admin/vitrina_users/user/?q=smolskait

![image](https://github.com/atviriduomenys/katalogas/assets/85924252/e2bd94f2-20ed-4520-8ab4-793fd543d977)
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/0b925da8-e080-452a-88c3-55e077a392b2)
![image](https://github.com/atviriduomenys/katalogas/assets/85924252/f39856df-4bf9-45ef-98ac-7512f1df6a95)

**Comment by JuliusLADP** [comment]
Tryniau testinėje aplinkoje julius.belickas@gmail.com (SAM koordinatorius) ir gavau tą pačią klaidą https://test.data.gov.lt/admin/vitrina_users/user/?q=Bel, 
kai paspaudžiau Taip esu tikras

![Image](https://github.com/atviriduomenys/katalogas/assets/69783864/6e7f34e0-8d41-47d0-bc12-7196db450e02)

**Comment by Faustasm** [comment]
```python
 Traceback (most recent call last):
   File "/X/site-packages/django/db/backends/base/base.py", line 242, in _commit
     return self.connection.commit()
            ^^^^^^^^^^^^^^^^^^^^^^^^
 psycopg2.errors.ForeignKeyViolation: update or delete on table "request" violates foreign key constraint "X" on table "request_organizations"
 DETAIL:  Key (id)=(X) is still referenced from table "request_organizations".
 
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/X/site-packages/django/core/handlers/exception.py", line 47, in inner
     response = get_response(request)
                ^^^^^^^^^^^^^^^^^^^^^
   File "/X/site-packages/django/core/handlers/base.py", line 181, in _get_response
     response = wrapped_callback(request, *callback_args, **callback_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/X/site-packages/django/contrib/admin/options.py", line 616, in wrapper
     return self.admin_site.admin_view(view)(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/X/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
     response = view_func(request, *args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/X/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
     response = view_func(request, *args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/X/site-packages/django/contrib/admin/sites.py", line 232, in inner
     return view(request, *args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/X/site-packages/django/utils/decorators.py", line 43, in _wrapper
     return bound_method(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/X/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
     response = view_func(request, *args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/X/site-packages/django/contrib/admin/options.py", line 1739, in changelist_view
     response = self.response_action(request, queryset=cl.get_queryset(request))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/X/site-packages/django/contrib/admin/options.py", line 1408, in response_action
     response = func(self, request, queryset)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/X/site-packages/django/contrib/admin/actions.py", line 45, in delete_selected
     modeladmin.delete_queryset(request, queryset)
   File "/X/site-packages/django/contrib/admin/options.py", line 1109, in delete_queryset
     queryset.delete()
   File "/X/site-packages/django/db/models/query.py", line 746, in delete
     deleted, _rows_count = collector.delete()
                            ^^^^^^^^^^^^^^^^^^
   File "/X/site-packages/django/db/models/deletion.py", line 400, in delete
     with transaction.atomic(using=self.using, savepoint=False):
   File "/X/site-packages/django/db/transaction.py", line 246, in __exit__
     connection.commit()
   File "/X/site-packages/django/utils/asyncio.py", line 33, in inner
     return func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
   File "/X/site-packages/django/db/backends/base/base.py", line 266, in commit
     self._commit()
   File "/X/site-packages/django/db/backends/base/base.py", line 241, in _commit
     with self.wrap_database_errors:
   File "/X/site-packages/django/db/utils.py", line 90, in __exit__
     raise dj_exc_value.with_traceback(traceback) from exc_value
   File "/X/site-packages/django/db/backends/base/base.py", line 242, in _commit
     return self.connection.commit()
            ^^^^^^^^^^^^^^^^^^^^^^^^
 django.db.utils.IntegrityError: update or delete on table "request" violates foreign key constraint "X" on table "request_organizations"
 DETAIL:  Key (id)=(X) is still referenced from table "request_organizations".
```
